export const BOARDING_HOUSES_FETCH_SUCCESS =
  "boardingHouses/BOARDING_HOUSES_FETCH_SUCCESS";

export const BOARDING_HOUSES_FETCH_USER_SUCCESS =
  "boardingHouses/BOARDING_HOUSES_FETCH_USER_SUCCESS";

export const BOARDING_HOUSE_BY_ID_FETCH_USER_SUCCESS =
  "boardingHouses/BOARDING_HOUSE_BY_ID_FETCH_USER_SUCCESS";

export const BOOKMARK_BY_ID_FETCH_USER_SUCCESS =
  "boardingHouses/BOOKMARK_BY_ID_FETCH_USER_SUCCESS";
